spring:
  application:
    name: taxpayer-service
  datasource:
    url: jdbc:postgresql://localhost:5432/turbotax
    username: turbotax
    password: turbotax
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082

aws:
  region: us-east-1
  secrets:
    jwt-secret-name: dev/turbotax/jwt
  kms:
    pii-key-alias: alias/turbotax-pii

jwt:
  expiry-minutes: 480

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${OTLP_ENDPOINT:http://localhost:4318/v1/traces}

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"
  level:
    com.turbotax: DEBUG
    org.springframework.security: INFO
